server:
  port: 9095
  servlet:
    session:
      timeout: 60m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj
    username: <username>
    password: <password>
  redis:
    host: localhost
    port: 6379
    password: <password>
    database: 1
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/ziheliu/ojbackend/dao/mybatis/*Mapper.xml
  type-aliases-package: com.ziheliu.ojbackend.model.entity
