server:
  port: 9095
  servlet:
    session:
      timeout: 60m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj
    username: <username>
    password: <password>
  redis:
    host: localhost
    port: 6379
    password: <password>
    database: 1
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/ziheliu/dao/mybatis/*Mapper.xml
  type-aliases-package: com.ziheliu.model.entity
runtime-path: /Users/liuzihe/MyFiles/Study/Project/java/oj/oj-portal/runtime
rocketmq:
  name-server: localhost:9876
  producer:
    group: oj-group
    send-message-timeout: 30000
